#DOWNLOAD THE BASE OF SERVER
FROM nginx:stable

# CREATE A WORKING DIRECTORY
WORKDIR /app/frontend

#COPY CODE FORM LOCAL MACHIEN TO THE HOST MACHINE
COPY . /app/frontend

#COPY CODE FORM REMOTE MACHINE TO NGINX SERVER
COPY . /usr/share/nginx/html

#PORT NUMBER 
EXPOSE 5500

#RUN THE SERVER
CMD ["nginx" , "-g" , "daemon off;"]
